/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app;

import java.awt.Color;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author yusrb
 */
public class BarangKeluarForm extends javax.swing.JFrame {

    /**
     * Creates new form UsersForm
     */
    
    private final String usernameForPage;
    private final String levelForPage;
    private final BarangKeluar barang_keluar_page;
    
    private String mode;
    
    private int barangMasukId;
    
    private int stockInId;
    
    private java.util.Map<String, Integer> produkMap = new java.util.HashMap<>();
    
    public BarangKeluarForm(BarangKeluar barangKeluar, String username, String level) {
        initComponents();
        conn = DBConnection.getConnection();
        loadProducts();
        
        if (SwingUtilities.isEventDispatchThread()) {
            if (cmbProduk.isShowing()) {
                cmbProduk.showPopup();
            }
        }
        this.usernameForPage = username;
        this.levelForPage = level;
        this.barang_keluar_page = barangKeluar;
        
        this.mode = "create";
        btnAction.setText("Create");
        btnAction.setBackground(Color.GREEN);
        
        setLocationRelativeTo(null);
        
        dtanggal.getDateEditor().addPropertyChangeListener("date", new PropertyChangeListener() {
            @Override
            public void propertyChange(PropertyChangeEvent evt) {
                txtJumlah.requestFocus();
            }
        });
    }
    
    public BarangKeluarForm(BarangKeluar barangKeluar, String username, String level, int id, String produkLama, int jumlahLama, java.util.Date tanggalKeluarDate, String keteranganLama, String adminLama) {
        this(barangKeluar, username, level);

        this.stockInId = id;
        this.mode = "update";

        btnAction.setText("Update");
        btnAction.setBackground(Color.BLUE);

        cmbProduk.setSelectedItem(produkLama);
        txtJumlah.setText(String.valueOf(jumlahLama));
        if (tanggalKeluarDate != null) {
            dtanggal.setDate(new java.util.Date(tanggalKeluarDate.getTime()));
        } else {
            dtanggal.setDate(null);
        }
        txtDeskripsi.setText(keteranganLama);
    }

    Connection conn;
    PreparedStatement pst;
    ResultSet rslt;

    public void loadProducts()
    {
        try {
            pst =  conn.prepareStatement("SELECT id, nama FROM products");
            rslt = pst.executeQuery();
            
            cmbProduk.removeAllItems();
            
            produkMap.clear();
            
            while (rslt.next())
            {
                int id = rslt.getInt("id");
                String nama = rslt.getString("nama");
                cmbProduk.addItem(nama);
                produkMap.put(nama, id);
            }
        } catch (SQLException ex) {
            Logger.getLogger(BarangKeluarForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
   
    private boolean cekStokCukup(int produkId, int jumlahDiminta)
    {
        try {
            PreparedStatement cekStok = conn.prepareStatement("SELECT stok FROM products WHERE id = ?");
            cekStok.setInt(1, produkId);
            ResultSet rs = cekStok.executeQuery();
            if (rs.next()) {
                return rs.getInt("stok") >= jumlahDiminta;
            }
            return false;
        } catch (SQLException ex) {
            Logger.getLogger(BarangKeluarForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        return false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnAction = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnBackToProducts = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDeskripsi = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        cmbProduk = new javax.swing.JComboBox<>();
        dtanggal = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        txtJumlah = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Barang Keluar Form Page");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel1.setText("Nama Produk");

        jPanel1.setBackground(new java.awt.Color(123, 104, 238));

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 42)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Stock In Form");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(205, 205, 205))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel4.setText("Deskripsi");

        btnAction.setForeground(new java.awt.Color(255, 255, 255));
        btnAction.setText("Action");
        btnAction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActionActionPerformed(evt);
            }
        });

        btnClear.setBackground(new java.awt.Color(102, 102, 102));
        btnClear.setForeground(new java.awt.Color(255, 255, 255));
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnBackToProducts.setBackground(new java.awt.Color(123, 104, 238));
        btnBackToProducts.setForeground(new java.awt.Color(255, 255, 255));
        btnBackToProducts.setText("Back");
        btnBackToProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackToProductsActionPerformed(evt);
            }
        });

        txtDeskripsi.setColumns(20);
        txtDeskripsi.setRows(5);
        txtDeskripsi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDeskripsiKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(txtDeskripsi);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel6.setText("Tanggal Keluar");

        cmbProduk.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbProduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbProdukActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel8.setText("Jumlah");

        txtJumlah.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtJumlahKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(230, 230, 230))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cmbProduk, 0, 302, Short.MAX_VALUE)
                                        .addGap(50, 50, 50)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(dtanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel8)
                                    .addComponent(txtJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnClear, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAction, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                            .addComponent(btnBackToProducts, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAction, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(dtanggal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbProduk, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnBackToProducts, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(127, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackToProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackToProductsActionPerformed
        // TODO add your handling code here:
        
        this.dispose();
    }//GEN-LAST:event_btnBackToProductsActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        
        cmbProduk.setSelectedIndex(0);
        txtJumlah.setText("");
        dtanggal.setDate(null);
        txtDeskripsi.setText("");

        cmbProduk.requestFocusInWindow();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnActionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActionActionPerformed
        // TODO add your handling code here:
        
        try {
                String produkDipilih = (String) cmbProduk.getSelectedItem();
                if (produkDipilih == null) {
                    JOptionPane.showMessageDialog(this, "Pilih produk!", "Input Kosong", JOptionPane.WARNING_MESSAGE);
                    return;
                }

                int idProduk = produkMap.getOrDefault(produkDipilih, -1);
                if (idProduk == -1) {
                    JOptionPane.showMessageDialog(this, "Produk tidak valid!", "Input Salah", JOptionPane.WARNING_MESSAGE);
                    return;
                }

                int jumlah;
                try {
                    jumlah = Integer.parseInt(txtJumlah.getText());
                    if (jumlah <= 0) {
                        JOptionPane.showMessageDialog(this, "Jumlah harus lebih dari 0", "Input Salah", JOptionPane.WARNING_MESSAGE);
                        return;
                    }
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(this, "Jumlah tidak valid!", "Input Salah", JOptionPane.WARNING_MESSAGE);
                    return;
                }

                java.util.Date tgl = dtanggal.getDate();
                if (tgl == null) {
                    JOptionPane.showMessageDialog(this, "Tanggal harus diisi!", "Input Kosong", JOptionPane.WARNING_MESSAGE);
                    return;
                }
                Timestamp tanggal = new Timestamp(tgl.getTime());

                String keterangan = txtDeskripsi.getText().trim();
                if (keterangan.isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Keterangan harus diisi!", "Input Kosong", JOptionPane.WARNING_MESSAGE);
                    return;
                }

                if (!cekStokCukup(idProduk, jumlah)) {
                    JOptionPane.showMessageDialog(this, "Stok tidak cukup!", "Stok Kurang", JOptionPane.WARNING_MESSAGE);
                    return;
                }

                pst = conn.prepareStatement(
                    "INSERT INTO barang_keluar(tanggal, id_barang, jumlah, keterangan, admin) VALUES (?, ?, ?, ?, ?)"
                );
                pst.setTimestamp(1, tanggal);
                pst.setInt(2, idProduk);
                pst.setInt(3, jumlah);
                pst.setString(4, keterangan);
                pst.setString(5, usernameForPage);

                int hasil = pst.executeUpdate();

                if (hasil == 1) {
                    PreparedStatement updateStok = conn.prepareStatement("UPDATE products SET stok = stok - ? WHERE id = ?");
                    updateStok.setInt(1, jumlah);
                    updateStok.setInt(2, idProduk);
                    updateStok.executeUpdate();

                    JOptionPane.showMessageDialog(this, "Barang keluar berhasil disimpan!", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                    if (barang_keluar_page != null) {
                        barang_keluar_page.Fetch();
                    }
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(this, "Gagal menyimpan barang keluar!", "Gagal", JOptionPane.WARNING_MESSAGE);
                }

            } catch (Exception e) {
                Logger.getLogger(BarangKeluarForm.class.getName()).log(Level.SEVERE, null, e);
                JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
    }//GEN-LAST:event_btnActionActionPerformed

    private void cmbProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbProdukActionPerformed
        // TODO add your handling code here:
        
        SwingUtilities.invokeLater(() -> {
                if (dtanggal.isShowing()) {
                    dtanggal.getJCalendar().setVisible(true);
                }
            });
    }//GEN-LAST:event_cmbProdukActionPerformed

    private void txtJumlahKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtJumlahKeyPressed
        // TODO add your handling code here:
        
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER)
        {
            txtDeskripsi.requestFocus();
        }
    }//GEN-LAST:event_txtJumlahKeyPressed

    private void txtDeskripsiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDeskripsiKeyPressed
        // TODO add your handling code here:
        
         if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER)
        {
            btnAction.doClick();
        }
    }//GEN-LAST:event_txtDeskripsiKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BarangKeluarForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BarangKeluarForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BarangKeluarForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BarangKeluarForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BarangKeluarForm(null, "", "").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAction;
    private javax.swing.JButton btnBackToProducts;
    private javax.swing.JButton btnClear;
    private javax.swing.JComboBox<String> cmbProduk;
    private com.toedter.calendar.JDateChooser dtanggal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtDeskripsi;
    private javax.swing.JTextField txtJumlah;
    // End of variables declaration//GEN-END:variables
}
